on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        override: true
        toolchain: 1.70.0
        components: rustfmt, clippy
    - name: Fmt
      run: cargo fmt -- --check
    - name: Compile
      run: cargo check
    - name: Clippy
      run: cargo clippy -- -Dwarnings
